# Numpy - Activity File 1

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])

In [4]:
print(arr1)

[1 2 3]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr3 = np.array((1, 2, 3, 4, 5))
print(arr3)

[1 2 3 4 5]


In [8]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

In [9]:
arr4.shape

(3, 5)

In [10]:
arr4.ndim

2

In [11]:
arr4.size

15

In [12]:
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
arr4.dtype

dtype('int32')

In [14]:
arr5 = np.array([
	[
		[1, 2], [3, 4], [5, 6]
	], 
	[
		[7, 8], [9, 10], [11, 12]
	], 
	[
		[13, 14], [15, 16], [17, 18]
	]
])

In [15]:
arr5.shape
arr5.ndim
arr5.size
arr5.dtype

dtype('int32')

### Special Arrays

In [16]:
arr0 = np.zeros((3, 5), dtype='int')    # An array with 3x5 shape and all values as 0
print(arr0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [17]:
arr1s = np.ones((2, 8), dtype='float')   # An array with 2x8 shape and all values as 1.0
print(arr1s)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
arrfull = np.full((4, 4), 7)               # An array with 4x4 shape and all values as 7
print(arrfull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [19]:
arrId = np.eye(4)
print(arrId)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
arrSeq = np.arange(5)
arrSeq

array([0, 1, 2, 3, 4])

In [21]:
arrSeq2 = np.arange(2, 10, 2)
arrSeq2

array([2, 4, 6, 8])

In [23]:
equally_spaced_values = np.linspace(1, 3, 20)
equally_spaced_values

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [24]:
arr_r = np.random.rand(3, 4)   # 3x4 array with random values between 0 and 1 [0, 1)
arr_r

array([[0.76794494, 0.35373246, 0.18524091, 0.7288885 ],
       [0.86090847, 0.78955309, 0.52881996, 0.10460083],
       [0.6486446 , 0.7743004 , 0.79935593, 0.96923298]])

In [25]:
np.random.randn(2, 3)   # 2x3 array with random values from standard normal distribution

array([[-1.86256954,  0.55833311, -0.02089748],
       [-0.77613965,  1.29060059,  0.4847779 ]])

In [29]:
np.random.randint(5, 10, size=(4, 20))   # 3x7 array with random integers between 5 and 10 [5, 10)

array([[9, 5, 8, 8, 7, 8, 5, 6, 6, 6, 7, 9, 8, 5, 6, 5, 6, 6, 7, 6],
       [8, 9, 8, 9, 8, 5, 8, 7, 9, 8, 5, 6, 5, 5, 8, 7, 5, 7, 5, 5],
       [7, 8, 6, 6, 7, 5, 9, 9, 8, 8, 6, 6, 5, 9, 5, 5, 6, 7, 9, 9],
       [6, 8, 5, 7, 7, 9, 7, 7, 6, 5, 9, 7, 5, 5, 7, 8, 5, 9, 6, 9]])

In [30]:
arrA = np.array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9])
arrA = arrA.astype('int')
arrA

array([1, 2, 3, 4, 5, 6, 7, 8])