# Numpy - Activity File 1

In [61]:
import numpy as np

In [62]:
arr1 = np.array([1, 2, 3])

In [63]:
print(arr1)

[1 2 3]


In [64]:
type(arr1)

numpy.ndarray

In [65]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [66]:
arr3 = np.array((1, 2, 3, 4, 5))
print(arr3)

[1 2 3 4 5]


In [67]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

In [68]:
arr4.shape

(3, 5)

In [69]:
arr4.ndim

2

In [70]:
arr4.size

15

In [71]:
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [72]:
arr4.dtype

dtype('int32')

In [73]:
arr5 = np.array([
	[
		[1, 2], [3, 4], [5, 6]
	], 
	[
		[7, 8], [9, 10], [11, 12]
	], 
	[
		[13, 14], [15, 16], [17, 18]
	]
])

In [74]:
arr5.shape
arr5.ndim
arr5.size
arr5.dtype

dtype('int32')

### Special Arrays

In [76]:
arr0 = np.zeros((3, 5), dtype='int')    # An array with 3x5 shape and all values as 0
print(arr0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [77]:
arr1s = np.ones((2, 8), dtype='float')   # An array with 2x8 shape and all values as 1.0
print(arr1s)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [78]:
arrfull = np.full((4, 4), 7)               # An array with 4x4 shape and all values as 7
print(arrfull)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [80]:
arrId = np.eye(4)
print(arrId)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
