# Indexing, Slicing and Reshaping

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
arr[0]

10

In [3]:
arr[-1]

50

In [4]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2D[1, 2]

6

In [6]:
print(arr2D[2, -1])

9


In [7]:
arr2D[1, :]

array([4, 5, 6])

In [8]:
arr

array([10, 20, 30, 40, 50])

In [9]:
arr[1:4]

array([20, 30, 40])

In [10]:
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2D[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [12]:
arr2D[1, :]

array([4, 5, 6])

In [13]:
arr2 = np.array([1, 2, 3, 4, 5])
mask = arr2 < 3
arr2[mask]

array([1, 2])

In [15]:
arr = np.array([10, 20, 30, 40, 50])
indexes = [0, 2, 4]
print(arr[indexes])

[10 30 50]


In [16]:
arr = np.arange(1, 13, 1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
arr = arr.reshape(4, 3)
print(arr)
arr = arr.reshape(6, 2)
arr

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [21]:
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr2 = arr2.flatten()
arr2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
arr3 = np.array([1, 2, 3])
arr3_2d = arr3[np.newaxis, :]
arr3_2d

array([[1, 2, 3]])

In [24]:
arr3_2d_cols = arr3[:, np.newaxis]
arr3_2d_cols

array([[1],
       [2],
       [3]])