# Array Operations and Broadcasting

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

In [3]:
print(a1 + a2)  # Element-wise addition
print(a1 * a2)  # Element-wise multiplication
print(a1 - a2)  # Element-wise subtraction
print(a1 / a2)  # Element-wise division

[5 7 9]
[ 4 10 18]
[-3 -3 -3]
[0.25 0.4  0.5 ]


In [5]:
a1 + 10 # Broadcasting: adding scalar to array

array([11, 12, 13])

In [7]:
arr2 = np.array([1, 4, 9, 16])
print(np.sqrt(arr2))  # Square root of each element
print(np.log(arr2))   # Natural logarithm of each element
print(np.exp(arr2))   # Exponential of each element
print(np.sin(arr2))   # Sine of each element (in radians)
print(np.cos(arr2))   # Cosine of each element (in radians)

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [8]:
arr4 = np.array([[10, 20, 30], [40, 50, 60]])
np.sum(arr4)

210

In [9]:
np.sum(arr4, axis=0)  # Sum along columns

array([50, 70, 90])

In [10]:
np.sum(arr4, axis=1)  # Sum along rows

array([ 60, 150])

In [11]:
np.mean(arr4)  # Mean of all elements
np.max(arr4)   # Maximum element
np.min(arr4)   # Minimum element
np.std(arr4)   # Standard deviation of all elements

17.07825127659933

In [12]:
arr5 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr6 = np.array([10, 20, 30])
arr5 + arr6

array([[11, 22, 33],
       [14, 25, 36]])